[package]
name = "pipeviewer"
version = "0.1.0"
authors = ["Benjamin Kästner <benjamin.kaestner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
indicatif = "0.15.0"
structopt = "0.3"
